# MEME Motifs #
Let's compare with motifs found by MEME
```{r}
# Loading process
names = c("motif", "gene_id", "distance", "number")
meme.bi = read.table("../motifs_extraction/26may14MEMEMotifs.bi.res", col.names=names)
meme.ca = read.table("../motifs_extraction/26may14MEMEMotifs.ca.res", col.names=names)
meme.sex = read.table("../motifs_extraction/26may14MEMEMotifs.sex.res", col.names=names)
meme.tet = read.table("../motifs_extraction/26may14MEMEMotifs.tet.res", col.names=names)
```

Typical function to classify motifs
```{r}
meme.modifier <- function(meme_table, exp_file) {
  # Expression of genes that contain the motif
  meme_match = exp_file[match(meme_table$gene_id, exp_file$gene_id, nomatch=0),] 
  # Expression of genes without the motif
  meme_no = exp_file[!match(exp_file$gene_id, meme_table$gene_id, nomatch=0),]
  # Compare if the means, null hypothesis: means are equal (better than t-test besexuse non-normal distribution)
  w.test = wilcox.test(meme_match$xp, meme_no$xp)
  print(w.test$p.value)
  if (w.test$p.value < pval.thre) {
    
    # If genes with motif are more expressed, the motif is increasing expression
    if (mean(meme_match$xp > mean(meme_no$xp))) {
      classifier = "high"
    } else {
      classifier = "low"
    }
  }
  else {
    classifier = NA
  }
}
```

Let's have a look at different motifs matches

```{r}
meme.bi.classify = data.frame()
meme.bi.motifs = unique(meme.bi$motif)
meme.bi.mod = rep(NA, length(meme.bi.motifs))
for (i in 1:length(meme.bi.motifs)) {
  meme.bi_match = meme.bi[meme.bi.motifs == meme.bi.motifs[i], ]
  if (length(meme.bi_match[,1]) > 3) {
   bi.mod = meme.modifier(meme.bi_match, exp_bi) 
   meme.bi.mod[i] = bi.mod
  }  
}

meme.bi.table = data.frame(as.character(meme.bi.motifs), meme.bi.mod)

# To search a motif
meme.bi.table[grep(".*TTCTAGAA.*", meme.bi.table$motif),]
```

We have some good sexndidates we want to search in known motifs
```{r}
sexnd = read.table("../goodcandidatesMotifs.txt", h=F, col.names=c("motif"))
```
```{r}
match.list = NULL
motifs.list = NULL
test = data.frame()
for (i in 1:length(sexnd[,1])) {
  match = length(meme.bi.table[grep(paste(".*", paste(sexnd[i,], ".*", sep=""), sep= ""), meme.bi.table$motif),1])
  if (match > 0) {
    t = meme.bi.table[grep(paste(".*", paste(sexnd[i,], ".*", sep=""), sep= ""), meme.bi.table$motif),]
    match.list = c(match.list, match)
    motifs.list = c(motifs.list, as.character(sexnd[i,1]))
    test = rbind(test,t)
  }
}
match.motifs = data.frame(motifs.list, match.list)
colnames(match.motifs) = c("motif", "match")
length(match.motifs[,1])
length(sexnd[,1])
```

We found 18 out of 46 good sexndidates motif that are matching, among a total of 51 good sexnditates.

If we try to classify motifs on other Paramecium species
````{r}
meme.ca.classify = data.frame()
meme.ca.motifs = unique(meme.ca$motif)
meme.ca.mod = rep(NA, length(meme.ca.motifs))
for (i in 1:length(meme.ca.motifs)) {
  meme.ca_match = meme.ca[meme.ca.motifs == meme.ca.motifs[i], ]
  if (length(meme.ca_match[,1]) > 3) {
   ca.mod = meme.modifier(meme.ca_match, exp_ca) 
   meme.ca.mod[i] = ca.mod
  }  
}

meme.ca.table = data.frame(as.character(meme.ca.motifs), meme.ca.mod)
```

````{r}
meme.sex.classify = data.frame()
meme.sex.motifs = unique(meme.sex$motif)
meme.sex.mod = rep(NA, length(meme.sex.motifs))
for (i in 1:length(meme.sex.motifs)) {
  meme.sex_match = meme.sex[meme.sex.motifs == meme.sex.motifs[i], ]
  if (length(meme.sex_match[,1]) > 3) {
   sex.mod = meme.modifier(meme.sex_match, exp_sex) 
   meme.sex.mod[i] = sex.mod
  }  
}

meme.sex.table = data.frame(as.character(meme.sex.motifs), meme.sex.mod)
```

````{r}
meme.tet.classify = data.frame()
meme.tet.motifs = unique(meme.tet$motif)
meme.tet.mod = rep(NA, length(meme.tet.motifs))
for (i in 1:length(meme.tet.motifs)) {
  meme.tet_match = meme.tet[meme.tet.motifs == meme.tet.motifs[i], ]
  if (length(meme.tet_match[,1]) > 3) {
   tet.mod = meme.modifier(meme.tet_match, exp_tet) 
   meme.tet.mod[i] = tet.mod
  }  
}

meme.tet.table = data.frame(as.character(meme.tet.motifs), meme.tet.mod)
```